{% set name = "aiida-crystal17" %}
{% set version = "0.9.0b5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bcd74ab89b801c16e6f41401f203ad108723f08667f6f46d1bf750754e3459b7

build:
  number: 0
  entry_points:
    - mock_crystal17 = aiida_crystal17.tests.mock_runcry17:main
    - mock_properties17 = aiida_crystal17.tests.mock_properties17:main
    - mock_gulp = aiida_crystal17.tests.mock_gulp:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  skip: True  # [win or py > 36]

requirements:
  host:
    - pip
    - python
    - reentry >=1.3.0
    - setuptools
  run:
    - aiida-core ==1.0.0b5
    - ase >=3.12.0,<4.0.0
    - jsonextended >=0.7.10
    - jsonschema
    # TODO these are the requirements in aiida-core[atomic_tools]
    # but pycifrw only available from 4.3 on conda-forge
    # - pycifrw ==4.2.1  # [py <= 27]
    # - pycifrw ==4.4  # [py > 27]
    - pycifrw ==4.4
    - python
    - ruamel.yaml
    - six
    - spglib >=1.10.0,<2.0.0

test:
  imports:
    - aiida_crystal17
    - aiida_crystal17.calcfunctions
    - aiida_crystal17.calculations
    - aiida_crystal17.cmndline
    - aiida_crystal17.common
    - aiida_crystal17.data
    - aiida_crystal17.gulp
    - aiida_crystal17.gulp.calculations
    - aiida_crystal17.gulp.cmndline
    - aiida_crystal17.gulp.data
    - aiida_crystal17.gulp.parsers
    - aiida_crystal17.gulp.parsers.raw
    - aiida_crystal17.gulp.potentials
    - aiida_crystal17.immigration
    - aiida_crystal17.parsers
    - aiida_crystal17.parsers.raw
    - aiida_crystal17.symmetry
    - aiida_crystal17.tests
    - aiida_crystal17.validation
    - aiida_crystal17.workflows
    - aiida_crystal17.workflows.common
    - aiida_crystal17.workflows.crystal_main
    - aiida_crystal17.workflows.crystal_props
  commands:
    - mock_crystal17 --test
    - mock_properties17 --test
    - mock_gulp --test

about:
  home: https://github.com/chrisjsewell/aiida-crystal17
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: AiiDA plugin for running the CRYSTAL17 code
  doc_url: https://aiida-crystal17.readthedocs.io
  dev_url: https://github.com/chrisjsewell/aiida-crystal17

extra:
  recipe-maintainers:
    - chrisjsewell
