{% set name = "aiida-crystal17" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8a21dcf6137092ebb3e1e35c3385debbb7f8e5d29986dd2754944bf84af1ee81

build:
  number: 0
  entry_points:
    - mock_crystal17 = aiida_crystal17.tests.mock_crystal17:main
    - mock_properties17 = aiida_crystal17.tests.mock_properties17:main
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  skip: true  # [win or py < 35 or py > 38]

requirements:
  host:
    - pip
    - python
    - reentry >=1.3.0
    - setuptools
  run:
    - aiida-core >=1.4.0,<2.0.0
    - ase >=3.12.0,<4.0.0
    - importlib_resources
    - jsonextended >=0.7.10
    - jsonschema
    - pycifrw >=4.4.1,<5.0.0
    - python
    - pyyaml
    - spglib >=1.10.0,<2.0.0

test:
  imports:
    - aiida_crystal17
    - aiida_crystal17.calcfunctions
    - aiida_crystal17.calculations
    - aiida_crystal17.cmndline
    - aiida_crystal17.common
    - aiida_crystal17.data
    - aiida_crystal17.immigration
    - aiida_crystal17.parsers
    - aiida_crystal17.parsers.raw
    - aiida_crystal17.symmetry
    - aiida_crystal17.validation
    - aiida_crystal17.validation.schemas
    - aiida_crystal17.workflows
    - aiida_crystal17.workflows.crystal_main
    - aiida_crystal17.workflows.crystal_props
  commands:
    - mock_crystal17 --test
    - mock_properties17 --test

about:
  home: https://github.com/chrisjsewell/aiida-crystal17
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: AiiDA plugin for running the CRYSTAL17 code
  doc_url: https://aiida-crystal17.readthedocs.io
  dev_url: https://github.com/chrisjsewell/aiida-crystal17

extra:
  recipe-maintainers:
    - mbercx
    - chrisjsewell
